apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: makemyplan-ms
  name: prod-makemyplan-ms
  namespace: prod
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 33%
      maxSurge: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        environment: prod
        app: makemyplan-ms
    spec:
      containers:
        - name: application
          image: 340866772701.dkr.ecr.ap-south-1.amazonaws.com/makemyplan:<version>
          env:
          ports:
            - containerPort: 8080
              name: api
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 400m
              memory: 512Mi
